### ISSUE TITLE
[Feature Request] Introduce a GitHub action

### ISSUE THREAD

**Issue by Bad3r** [eramdam/starry-raindrop#1]
It is possible to remove the need to run this tool locally and automate running it on a schedule using GitHub actions

**Comment by eramdam** [comment]
1. For some reason I never have seen this issue until now 😅 
2. Huuuh, yeah I suppose there would be a way. I'll need to read about how to do that exactly 🤔

**Comment by eramdam** [comment]
Done. I added some documentation in the README. Let me know if something isn't clear.

**Comment by Bad3r** [comment]
Great thank you!
